# Generated by Django 5.0.6 on 2025-08-31 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_int", models.PositiveIntegerField()),
                ("outline_before", models.TextField(blank=True)),
                ("outline_after", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="core.entry",
                    ),
                ),
                (
                    "patch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_records",
                        to="core.patch",
                    ),
                ),
            ],
            options={
                "ordering": ["version_int", "id"],
            },
        ),
    ]
