# Generated by Django 5.0.14 on 2025-09-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_patch_to_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="change",
            name="target_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="core.entry",
            ),
        ),
    ]
