# Generated by Django 5.0.6 on 2025-09-18 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_change_project_alter_change_target_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.section",
            ),
        ),
    ]
